import io
import csv
from datetime import datetime
import pandas as pd
from flask import Blueprint, send_file, current_app, redirect, url_for, flash, make_response
from flask_login import login_required, current_user
from models import Feedback
from utils.decorators import requires_roles

# ReportLab imports for PDF generation
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

reports_bp = Blueprint('reports', __name__)

def get_filtered_query():
    """Helper to get feedback based on role"""
    query = Feedback.query
    if current_user.role == 'Student' or current_user.role == 'Staff':
        query = query.filter_by(user_id=current_user.id)
    elif current_user.role == 'HOD':
        query = query.filter_by(department_category=current_user.department)
    return query

@reports_bp.route('/excel')
@login_required
@requires_roles('Admin', 'HOD', 'Staff')
def download_excel():
    feedbacks = get_filtered_query().all()
    if not feedbacks:
        flash('No data available to generate report.', 'warning')
        return redirect(url_for('dashboard.index'))

    # Prepare data for pandas
    data = []
    for f in feedbacks:
        data.append({
            'ID': f.id,
            'Date': f.created_at.strftime('%Y-%m-%d %H:%M'),
            'Department/Category': f.department_category,
            'Original Text': f.original_text,
            'Cleaned Text': f.cleaned_text,
            'Sentiment': f.sentiment,
            'Score': f.sentiment_score
        })
        
    df = pd.DataFrame(data)
    
    # Save to BytesIO
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Sentiment Report')
        
    output.seek(0)
    
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"Sentiment_Report_{timestamp}.xlsx"
    
    response = make_response(output.getvalue())
    response.headers['Content-Disposition'] = f'attachment; filename={filename}'
    response.headers['Content-Type'] = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    return response

@reports_bp.route('/pdf')
@login_required
@requires_roles('Admin', 'HOD', 'Staff')
def download_pdf():
    feedbacks = get_filtered_query().order_by(Feedback.created_at.desc()).limit(100).all() # Limit for PDF readability
    if not feedbacks:
        flash('No data available to generate report.', 'warning')
        return redirect(url_for('dashboard.index'))
        
    output = io.BytesIO()
    doc = SimpleDocTemplate(output, pagesize=letter)
    elements = []
    
    styles = getSampleStyleSheet()
    title_style = styles['Heading1']
    normal_style = styles['Normal']
    
    elements.append(Paragraph("AI-Based Sentiment Analysis Report", title_style))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph(f"Generated by: {current_user.name} ({current_user.role})", normal_style))
    elements.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", normal_style))
    elements.append(Spacer(1, 24))
    
    # Table data
    data = [['ID', 'Date', 'Sentiment', 'Score', 'Department']]
    for f in feedbacks:
        data.append([
            str(f.id), 
            f.created_at.strftime('%Y-%m-%d'),
            f.sentiment,
            f"{f.sentiment_score:.2f}",
            str(f.department_category or 'N/A')
        ])
        
    # Table styling
    t = Table(data)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.grey),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 12),
        ('BACKGROUND', (0,1), (-1,-1), colors.beige),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    
    elements.append(t)
    doc.build(elements)
    
    output.seek(0)
    
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"Sentiment_Report_{timestamp}.pdf"
    
    response = make_response(output.getvalue())
    response.headers['Content-Disposition'] = f'attachment; filename={filename}'
    response.headers['Content-Type'] = 'application/pdf'
    return response

@reports_bp.route('/csv')
@login_required
@requires_roles('Admin', 'HOD', 'Staff')
def download_csv():
    feedbacks = get_filtered_query().all()
    if not feedbacks:
        flash('No data available to generate report.', 'warning')
        return redirect(url_for('dashboard.index'))

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(['ID', 'Date', 'Department', 'Original Text', 'Cleaned Text', 'Sentiment', 'Score'])
    for f in feedbacks:
        writer.writerow([
            f.id,
            f.created_at.strftime('%Y-%m-%d %H:%M'),
            f.department_category or 'N/A',
            f.original_text,
            f.cleaned_text,
            f.sentiment,
            f"{f.sentiment_score:.2f}"
        ])

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"Sentiment_Report_{timestamp}.csv"

    response = make_response(output.getvalue())
    response.headers['Content-Disposition'] = f'attachment; filename={filename}'
    response.headers['Content-Type'] = 'text/csv'
    return response
